name: Blazor3D

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/dotnet/Blazor3D/Blazor3D.sln
    - name: Build
      run: dotnet build --no-restore ./src/dotnet/Blazor3D/Blazor3D.sln
    - name: test
      run: dotnet test --no-build --verbosity normal ./src/dotnet/Blazor3D/Blazor3D.sln
